on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   my_test:
     runs-on: ubuntu-latest
     name: Install Bats and bats libs
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Setup Bats and bats libs
         id: setup-bats
         uses: bats-core/bats-action@3.0.0
         with:
           support-path: ${{ github_workspace }}/tests/test_helper/bats-support
           assert-path: ${{ github_workspace }}/tests/test_helper/bats-assert
       - name: ar.bash bats test
         shell: bash
         env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
         run: bats tests/test_ar.bats
